### PR TITLE
30 Create the Login page

### PR DESCRIPTION
**Pull request by ArmandoShala**
feat(loginpage): Created base for login page [30]

feat(loginpage): First proposal for login CSS [30]

feat(loginpage): Tweaked login page [30]

feat(loginpage): Tweaked login CSS [30]

feat(loginpage): Added form and some logic in login page [30]

### CODE REVIEW

**Comment by omerasipi** [comment]
Fixed automated testing please don't try to remap testing setup, just adapt the docs according to this working concept! The automated testing is only for backend stuff!

**Review by SilvanBaach — DISMISSED** [review]
There is code which does not work. Please double check

**Review by omerasipi — APPROVED** [review]
i have fixed the merge errors everything works as it should inlcuding the tests

**Review by omerasipi — APPROVED** [review]
looks amazing ~~spiderman~~

**Review by omerasipi — APPROVED** [review]

**Pull request merged**
