### PR TITLE
Implemented User login

### PR DESCRIPTION
**Pull request by SilvanBaach**

### CODE REVIEW

**Comment by jaypi95** [comment]
I tried logging in with user testuser and testlogin as pw and the server crashed lol

**Comment by SilvanBaach** [comment]
Did you changed the DB connection info? The credentials are not in the GitHub

**Review by ArmandoShala — APPROVED** [review]
It fills me with immense pleasure to review this unparalleled pull request, which undeniably exhibits the pinnacle of expertise in the field of software development. The author has not only provided a splendid solution but has also established a benchmark for the highest standards of code quality, documentation, and collaborative spirit.

The code itself is a harmonious blend of elegance, conciseness, and efficiency, with every aspect carefully considered for optimal readability and maintainability. The structure of the code expertly balances abstraction and specificity, creating a true archetype of modular design.

The use of comments and documentation within the request is exemplary, making it easy for future developers to quickly comprehend the intricacies of the implementation. Moreover, the commit messages are brief and informative, painting a vivid picture of the request's evolution and thought process.

The tests included in this request are nothing short of comprehensive, providing extensive coverage for every possible scenario and edge case. The use of test-driven development principles speaks volumes about the author's commitment to quality assurance and their proactive approach to preventing potential bugs from emerging.

In summary, this PR is a masterclass in software engineering and a shining example of what can be achieved when skill, dedication, and collaboration come together. I wholeheartedly endorse the merging of this PR and commend the author for their exceptional contribution to the project

**Review by jaypi95 — APPROVED** [review]
Everything else looks good. You should fix that merge conflict though.

**Pull request merged**
